### ISSUE TITLE
Make this repo a "template" repo

### ISSUE THREAD

**Issue by umar-tophat** [tophat/new-project-kit#4]
**Is your feature request related to a problem? Please describe.**

Creating a new repo based on this starter kit requires multiple steps.

**Describe the solution you'd like**

Use GitHub's new "Template repository" feature (found in the settings page) to make it easy as pie to create a new open source repo using this starter kit.

**Describe alternatives you've considered**

🤷‍♂ 

**Additional context**

![image](https://user-images.githubusercontent.com/38886386/59959113-f93faa00-947e-11e9-958b-f40ebe7821dc.png)

**Comment by msrose** [comment]
This is done!
